name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 27071:27071
        env:
          POSTGRES_DB: railway
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: xMvxNJYXtXeypDYjKwGxaxSfaiioyEpO
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Install Composer Dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Set Environment Variables
      run: |
        echo "APP_ENV=testing" >> .env
        echo "DB_CONNECTION=pgsql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=27071" >> .env
        echo "DB_DATABASE=railway" >> .env
        echo "DB_USERNAME=postgres" >> .env
        echo "DB_PASSWORD=xMvxNJYXtXeypDYjKwGxaxSfaiioyEpO" >> .env
        echo "APP_KEY=base64:A+k+JYLofZUJ8Hw1kISnlY092bTlZi8Wl/Uod/ZbzRM=" >> .env
        echo "REDIS_HOST=127.0.0.1" >> .env
        echo "REDIS_PASSWORD=null" >> .env
        echo "REDIS_PORT=6379" >> .env
        echo "MAIL_MAILER=log" >> .env
        echo "MAIL_HOST=127.0.0.1" >> .env
        echo "MAIL_PORT=2525" >> .env
        echo "MAIL_USERNAME=null" >> .env
        echo "MAIL_PASSWORD=null" >> .env
        echo "MAIL_ENCRYPTION=null" >> .env
        echo "MAIL_FROM_ADDRESS=\"hello@example.com\"" >> .env
        echo "MAIL_FROM_NAME=\"Laravel\"" >> .env

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Set Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Wait for PostgreSQL
      run: |
        until pg_isready -h 127.0.0.1 -p 27071; do
          echo "Waiting for PostgreSQL to be ready..."
          sleep 1
        done

    - name: Run Database Migrations
      run: php artisan migrate --force

    - name: Execute Tests
      run: php artisan test
      env:
        DB_CONNECTION: pgsql
        DB_HOST: 127.0.0.1
        DB_PORT: 27071
        DB_DATABASE: railway
        DB_USERNAME: postgres
        DB_PASSWORD: xMvxNJYXtXeypDYjKwGxaxSfaiioyEpO
